---
- name: Création d'une VM sur Proxmox
  hosts: localhost
  gather_facts: false
  tasks:
  
    - name: Créer une nouvelle VM QEMU
      community.proxmox.proxmox_kvm:
        node: "proj-cloudi2"
        api_host: "{{ lookup('env', 'PROXMOX_URL') }}"
        api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
        api_token_id: "{{ lookup('env', 'PROXMOX_TOKEN_ID') }}"
        api_token_secret: "{{ lookup('env', 'PROXMOX_TOKEN_SECRET') }}"
        validate_certs: false 

        # Configuration de la VM
        name: "vm-demo"
        vmid: 150
        target: "{{ pve_node }}"
        storage: "local-lvm"
        
        # Ressources
        memory: 2048
        cores: 2
        sockets: 1
        
        # Disque et Réseau
        disk: 5G
        netif: '{"net0":"virtio,bridge=vmbr0"}'
        
        # État souhaité
        state: present
