---
- name: Playbook de test minimaliste
  hosts: localhost
  gather_facts: false

  vars:
    message_test: "Hello ! pour le test."

  tasks:
    - name: Afficher le message de confirmation
      debug:
        msg: "{{ message_test }}"

    - name: Simuler une étape de déploiement
      ansible.builtin.pause:
        seconds: 2
        prompt: "en cours..."

    - name: Message final
      debug:
        msg: "Test terminé AWX communique bien avec le dépôt Git."
