---
- name: Création d'une VM sur Proxmox
  hosts: localhost
  gather_facts: false
  
  tasks:
    - name: install proxmoxer
      pip:
        name: proxmoxer
    - name: Trouver le prochain VMID disponible
      delegate_to: localhost
      uri:
        url: "https://{{ lookup('env', 'PROXMOX_HOST') }}:8006/api2/json/cluster/nextid"
        method: GET
        headers:
          Authorization: "PVEAPIToken={{ lookup('env', 'PROXMOX_USER') }}!{{ lookup('env', 'PROXMOX_TOKEN_ID') }}={{ lookup('env', 'PROXMOX_TOKEN_SECRET') }}"
        validate_certs: false
      register: next_id_response
      
    - name: Créer une nouvelle VM QEMU
      community.proxmox.proxmox:
        node: "pve"
        
        api_host: "{{ lookup('env', 'PROXMOX_HOST') }}"
        api_port: "{{ lookup('env', 'PROXMOX_PORT') }}"
        api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
        api_token_id: "{{ lookup('env', 'PROXMOX_TOKEN_ID') }}"
        api_token_secret: "{{ lookup('env', 'PROXMOX_TOKEN_SECRET') }}"
        validate_certs: false 

        hostname: "{{ vm_name }}"
        vmid: "{{ next_id_response.json.data }}"
        cores: "{{ cpu }}"
        memory: "{{ ram }}"
        ostemplate: local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst

        features: "nesting=1"
        
        storage: local-lvm
        password: "root123"
        
        state: started
