---
- name: Création d'une VM ajout dans bind 9
  hosts: localhost
  gather_facts: false
  vars:
    vm_name: "{{ vm_name }}"
    vm_user: "{{ vm_user }}"
  tasks:
    - name: install proxmoxer
      pip:
        name: proxmoxer
        
    - name: install dnspython
      pip:
        name: dnspython
        
    - name: Générer le cloud-init
      template:
        src: user_data.yaml.j2
        dest: "/var/lib/vz/snippets/user_{{ vm_name }}.yaml"
      delegate_to: proxmox
  
    - name: Cloner la VM depuis le Template
      community.proxmox.proxmox_kvm:
        node: "proj-cloudi2"
        api_host: "{{ lookup('env', 'PROXMOX_HOST') }}"
        api_port: "{{ lookup('env', 'PROXMOX_PORT') }}"
        api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
        api_token_id: "{{ lookup('env', 'PROXMOX_TOKEN_ID') }}"
        api_token_secret: "{{ lookup('env', 'PROXMOX_TOKEN_SECRET') }}"
        validate_certs: false
        
        name: "{{ vm_name }}"
        clone: "template-ubuntu-2404"
        full: true
        storage: local-lvm
        cores: "{{ cores }}"
        memory: "{{ memory }}"
        
        format: qcow2
        timeout: 500
        state: present
        
    - name: Resize disque
      community.proxmox.proxmox_disk:
        name: "{{ vm_name }}"
        disk: scsi0
        size: "{{ size_disk }}G"
        state: resized
        
    - name: Appliquer la configuration Cloud-init custom
      community.proxmox.proxmox_kvm:
        node: "proj-cloudi2"
        api_host: "{{ lookup('env', 'PROXMOX_HOST') }}"
        api_port: "{{ lookup('env', 'PROXMOX_PORT') }}"
        api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
        api_token_id: "{{ lookup('env', 'PROXMOX_TOKEN_ID') }}"
        api_token_secret: "{{ lookup('env', 'PROXMOX_TOKEN_SECRET') }}"
        validate_certs: false
        
        name: "{{ vm_name }}"
        update: true
        
        citype: nocloud
        cicustom: "user=local:snippets/user_{{ vm_name }}.yaml"
        ipconfig:
          ipconfig0: "ip=dhcp"
        
    - name: Démarrer la VM 
      community.proxmox.proxmox_kvm:
        node: "proj-cloudi2"
        api_host: "{{ lookup('env', 'PROXMOX_HOST') }}"
        api_port: "{{ lookup('env', 'PROXMOX_PORT') }}"
        api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
        api_token_id: "{{ lookup('env', 'PROXMOX_TOKEN_ID') }}"
        api_token_secret: "{{ lookup('env', 'PROXMOX_TOKEN_SECRET') }}"
        validate_certs: false
        
        name: "{{ vm_name }}"
        state: started
      
    - name: Attendre que la VM monte
      pause:
        seconds: 40
        
    - name: Lancer sync via API
      uri:
        url: "{{ awx_url }}/api/v2/inventory_sources/{{ source_id }}/update/"
        method: POST
        user: "{{ awx_user }}"
        password: "{{ awx_password }}"
        force_basic_auth: yes
        validate_certs: false
        status_code: [200, 202]
      register: inventory_sync

    - name: Attendre la fin du sync
      pause:
        seconds: 5
        
    - name: Stocker l'IP de eth0
      set_fact:
        vm_ip: >-
          {{
            hostvars[vm_name]['proxmox_agent_interfaces']
            | selectattr('name', 'equalto', 'eth0')
            | map(attribute='ip-addresses')
            | first
            | reject('search', ':')
            | map('regex_replace', '/.*$', '')
            | first
          }}
    
    - name: Ajouter une entrée DNS dans BIND9
      community.general.nsupdate:
        server: "{{ lookup('env', 'DNS_SERVER_IP') }}"
        zone: "icube.local"
        record: "{{ vm_name }}"
        type: "A"
        value: "{{ vm_ip }}"
        ttl: 300
        state: present
        key_name: "{{ lookup('env', 'DNS_KEY_NAME') }}"
        key_secret: "{{ lookup('env', 'DNS_KEY_SECRET') }}"
        key_algorithm: "hmac-sha256"
